creation_rules:
  - encrypted_regex: '^(user.*|pass.*)$'
    filename_regex: '\.(yaml|yml|json)$'
    key_groups:
      - age:
        - <YOUR_AGE_PUBLIC_KEY>
stores:
  yaml:
    indent: 2
  json:
    indent: 2

